### ISSUE TITLE
Honor secrets.yml environments

### ISSUE THREAD

**Issue by rascoro1** [cyberark/conjur-azure-devops-extension#5]
## Is your feature request related to a problem? Please describe.
secrets.yml allows for the ability to set environments. Such as `dev` , `qa` , `prod` and each one of these environments could reference different secrets. 

## Describe the solution you would like
I would like the ability within this extension to specify which environment to retrieve the secrets from. 
```
common:
  DB_USER: db-user
  DB_NAME: db-name
  DB_HOST: db-host.example.com

staging:
  DB_PASS: some_password

production:
  DB_PASS: other_password
  ```
